version: "1"

services:
  chatgpt_telegram_bot1:
    container_name: chatgpt_telegram_bot_pi
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile

